# Generated by Django 4.0.5 on 2022-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
