# Generated by Django 4.0.5 on 2022-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0007_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
