# Generated by Django 4.0.5 on 2022-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0008_task_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='rating',
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
